# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JWDVideoPlayEdit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JWDVideoPlayEdit

  target 'JWDVideoPlayEditTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JWDVideoPlayEditUITests' do
    inherit! :search_paths
    # Pods for testing
  end

    pod 'Masonry', '1.0.2'


end
